/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.jooq.tables.records;


import br.com.wdc.shopping.persistence.jooq.tables.EnProduct;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EnProductRecord extends UpdatableRecordImpl<EnProductRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.EN_PRODUCT.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.EN_PRODUCT.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.EN_PRODUCT.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.EN_PRODUCT.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.EN_PRODUCT.PRICE</code>.
     */
    public void setPrice(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.EN_PRODUCT.PRICE</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>PUBLIC.EN_PRODUCT.DESCRIPTION</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.EN_PRODUCT.DESCRIPTION</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.EN_PRODUCT.IMAGE</code>.
     */
    public void setImage(byte[] value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.EN_PRODUCT.IMAGE</code>.
     */
    public byte[] getImage() {
        return (byte[]) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EnProductRecord
     */
    public EnProductRecord() {
        super(EnProduct.EN_PRODUCT);
    }

    /**
     * Create a detached, initialised EnProductRecord
     */
    public EnProductRecord(Long id, String name, BigDecimal price, String description, byte[] image) {
        super(EnProduct.EN_PRODUCT);

        setId(id);
        setName(name);
        setPrice(price);
        setDescription(description);
        setImage(image);
        resetChangedOnNotNull();
    }
}
