/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.jooq.tables.records;


import br.com.wdc.shopping.persistence.jooq.tables.EnPurchase;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EnPurchaseRecord extends UpdatableRecordImpl<EnPurchaseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.EN_PURCHASE.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.EN_PURCHASE.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.EN_PURCHASE.USERID</code>.
     */
    public void setUserid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.EN_PURCHASE.USERID</code>.
     */
    public Long getUserid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.EN_PURCHASE.BUYDATE</code>.
     */
    public void setBuydate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.EN_PURCHASE.BUYDATE</code>.
     */
    public LocalDateTime getBuydate() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EnPurchaseRecord
     */
    public EnPurchaseRecord() {
        super(EnPurchase.EN_PURCHASE);
    }

    /**
     * Create a detached, initialised EnPurchaseRecord
     */
    public EnPurchaseRecord(Long id, Long userid, LocalDateTime buydate) {
        super(EnPurchase.EN_PURCHASE);

        setId(id);
        setUserid(userid);
        setBuydate(buydate);
        resetChangedOnNotNull();
    }
}
