/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.jooq.tables.records;


import br.com.wdc.shopping.persistence.jooq.tables.EnPurchaseitem;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EnPurchaseitemRecord extends UpdatableRecordImpl<EnPurchaseitemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.EN_PURCHASEITEM.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.EN_PURCHASEITEM.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.EN_PURCHASEITEM.PURCHASEID</code>.
     */
    public void setPurchaseid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.EN_PURCHASEITEM.PURCHASEID</code>.
     */
    public Long getPurchaseid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.EN_PURCHASEITEM.PRODUCTID</code>.
     */
    public void setProductid(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.EN_PURCHASEITEM.PRODUCTID</code>.
     */
    public Long getProductid() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>PUBLIC.EN_PURCHASEITEM.AMOUNT</code>.
     */
    public void setAmount(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.EN_PURCHASEITEM.AMOUNT</code>.
     */
    public Integer getAmount() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>PUBLIC.EN_PURCHASEITEM.PRICE</code>.
     */
    public void setPrice(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.EN_PURCHASEITEM.PRICE</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EnPurchaseitemRecord
     */
    public EnPurchaseitemRecord() {
        super(EnPurchaseitem.EN_PURCHASEITEM);
    }

    /**
     * Create a detached, initialised EnPurchaseitemRecord
     */
    public EnPurchaseitemRecord(Long id, Long purchaseid, Long productid, Integer amount, BigDecimal price) {
        super(EnPurchaseitem.EN_PURCHASEITEM);

        setId(id);
        setPurchaseid(purchaseid);
        setProductid(productid);
        setAmount(amount);
        setPrice(price);
        resetChangedOnNotNull();
    }
}
