/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.jooq.tables.records;


import br.com.wdc.shopping.persistence.jooq.tables.EnUser;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EnUserRecord extends UpdatableRecordImpl<EnUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.EN_USER.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.EN_USER.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.EN_USER.USERNAME</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.EN_USER.USERNAME</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.EN_USER.PASSWORD</code>.
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.EN_USER.PASSWORD</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.EN_USER.NAME</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.EN_USER.NAME</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.EN_USER.ROLES</code>.
     */
    public void setRoles(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.EN_USER.ROLES</code>.
     */
    public String getRoles() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EnUserRecord
     */
    public EnUserRecord() {
        super(EnUser.EN_USER);
    }

    /**
     * Create a detached, initialised EnUserRecord
     */
    public EnUserRecord(Long id, String username, String password, String name, String roles) {
        super(EnUser.EN_USER);

        setId(id);
        setUsername(username);
        setPassword(password);
        setName(name);
        setRoles(roles);
        resetChangedOnNotNull();
    }
}
