/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.impl.jooq.routines;


import br.com.wdc.shopping.persistence.impl.jooq.Public;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ToBase64 extends AbstractRoutine<String> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>PUBLIC.TO_BASE64.RETURN_VALUE</code>.
     */
    public static final Parameter<String> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>PUBLIC.TO_BASE64.P1</code>.
     */
    public static final Parameter<byte[]> P1 = Internal.createParameter("P1", SQLDataType.VARBINARY(1000000000), false, false);

    /**
     * Create a new routine call instance
     */
    public ToBase64() {
        super("TO_BASE64", Public.PUBLIC, SQLDataType.VARCHAR);

        setReturnParameter(RETURN_VALUE);
        addInParameter(P1);
    }

    /**
     * Set the <code>P1</code> parameter IN value to the routine
     */
    public void setP1(byte[] value) {
        setValue(P1, value);
    }

    /**
     * Set the <code>P1</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void setP1(Field<byte[]> field) {
        setField(P1, field);
    }
}
