/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.impl.scheme.tables;


import br.com.wdc.shopping.persistence.impl.scheme.Keys;
import br.com.wdc.shopping.persistence.impl.scheme.Public;
import br.com.wdc.shopping.persistence.impl.scheme.tables.EnPurchaseitem.EnPurchaseitemPath;

import java.math.BigDecimal;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EnProduct extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC.EN_PRODUCT</code>
     */
    public static final EnProduct EN_PRODUCT = new EnProduct();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>PUBLIC.EN_PRODUCT.ID</code>.
     */
    public final TableField<Record, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.EN_PRODUCT.NAME</code>.
     */
    public final TableField<Record, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(1000000).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.EN_PRODUCT.PRICE</code>.
     */
    public final TableField<Record, BigDecimal> PRICE = createField(DSL.name("PRICE"), SQLDataType.DECIMAL(20, 2).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.EN_PRODUCT.DESCRIPTION</code>.
     */
    public final TableField<Record, String> DESCRIPTION = createField(DSL.name("DESCRIPTION"), SQLDataType.VARCHAR(1000000).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.EN_PRODUCT.IMAGE</code>.
     */
    public final TableField<Record, byte[]> IMAGE = createField(DSL.name("IMAGE"), SQLDataType.BINARY(1000000), this, "");

    private EnProduct(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private EnProduct(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>PUBLIC.EN_PRODUCT</code> table reference
     */
    public EnProduct(String alias) {
        this(DSL.name(alias), EN_PRODUCT);
    }

    /**
     * Create an aliased <code>PUBLIC.EN_PRODUCT</code> table reference
     */
    public EnProduct(Name alias) {
        this(alias, EN_PRODUCT);
    }

    /**
     * Create a <code>PUBLIC.EN_PRODUCT</code> table reference
     */
    public EnProduct() {
        this(DSL.name("EN_PRODUCT"), null);
    }

    public <O extends Record> EnProduct(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, EN_PRODUCT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class EnProductPath extends EnProduct implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> EnProductPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private EnProductPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public EnProductPath as(String alias) {
            return new EnProductPath(DSL.name(alias), this);
        }

        @Override
        public EnProductPath as(Name alias) {
            return new EnProductPath(alias, this);
        }

        @Override
        public EnProductPath as(Table<?> alias) {
            return new EnProductPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.PK_PRODUCT;
    }

    private transient EnPurchaseitemPath _enPurchaseitem;

    /**
     * Get the implicit to-many join path to the
     * <code>PUBLIC.EN_PURCHASEITEM</code> table
     */
    public EnPurchaseitemPath enPurchaseitem() {
        if (_enPurchaseitem == null)
            _enPurchaseitem = new EnPurchaseitemPath(this, null, Keys.FK_PURCHASEITEM_PRODUCT.getInverseKey());

        return _enPurchaseitem;
    }

    @Override
    public EnProduct as(String alias) {
        return new EnProduct(DSL.name(alias), this);
    }

    @Override
    public EnProduct as(Name alias) {
        return new EnProduct(alias, this);
    }

    @Override
    public EnProduct as(Table<?> alias) {
        return new EnProduct(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public EnProduct rename(String name) {
        return new EnProduct(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EnProduct rename(Name name) {
        return new EnProduct(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public EnProduct rename(Table<?> name) {
        return new EnProduct(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnProduct where(Condition condition) {
        return new EnProduct(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnProduct where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnProduct where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnProduct where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EnProduct where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EnProduct where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EnProduct where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EnProduct where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnProduct whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnProduct whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
