// @formatter:off
/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.impl.scheme.tables;


import br.com.wdc.shopping.persistence.impl.scheme.Public;

import java.math.BigDecimal;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EnPurchaseitem extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    public static final EnPurchaseitem EN_PURCHASEITEM = new EnPurchaseitem();

    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    public final TableField<Record, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false), this, "");

    public final TableField<Record, Long> PURCHASEID = createField(DSL.name("PURCHASEID"), SQLDataType.BIGINT.nullable(false), this, "");

    public final TableField<Record, Long> PRODUCTID = createField(DSL.name("PRODUCTID"), SQLDataType.BIGINT.nullable(false), this, "");

    public final TableField<Record, Integer> AMOUNT = createField(DSL.name("AMOUNT"), SQLDataType.INTEGER.nullable(false), this, "");

    public final TableField<Record, BigDecimal> PRICE = createField(DSL.name("PRICE"), SQLDataType.DECIMAL(20, 2).nullable(false), this, "");

    private EnPurchaseitem(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private EnPurchaseitem(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    public EnPurchaseitem(String alias) {
        this(DSL.name(alias), EN_PURCHASEITEM);
    }

    public EnPurchaseitem(Name alias) {
        this(alias, EN_PURCHASEITEM);
    }

    public EnPurchaseitem() {
        this(DSL.name("EN_PURCHASEITEM"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(EnPurchaseitem.EN_PURCHASEITEM, DSL.name("PK_PURCHASEITEM"), new TableField[] { EnPurchaseitem.EN_PURCHASEITEM.ID }, true);
    }

    @Override
    public EnPurchaseitem as(String alias) {
        return new EnPurchaseitem(DSL.name(alias), this);
    }

    @Override
    public EnPurchaseitem as(Name alias) {
        return new EnPurchaseitem(alias, this);
    }

    @Override
    public EnPurchaseitem as(Table<?> alias) {
        return new EnPurchaseitem(alias.getQualifiedName(), this);
    }

    @Override
    public EnPurchaseitem rename(String name) {
        return new EnPurchaseitem(DSL.name(name), null);
    }

    @Override
    public EnPurchaseitem rename(Name name) {
        return new EnPurchaseitem(name, null);
    }

    @Override
    public EnPurchaseitem rename(Table<?> name) {
        return new EnPurchaseitem(name.getQualifiedName(), null);
    }

    @Override
    public EnPurchaseitem where(Condition condition) {
        return new EnPurchaseitem(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    @Override
    public EnPurchaseitem where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    @Override
    public EnPurchaseitem where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    @Override
    public EnPurchaseitem where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    @Override
    @PlainSQL
    public EnPurchaseitem where(SQL condition) {
        return where(DSL.condition(condition));
    }

    @Override
    @PlainSQL
    public EnPurchaseitem where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    @Override
    @PlainSQL
    public EnPurchaseitem where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    @Override
    @PlainSQL
    public EnPurchaseitem where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    @Override
    public EnPurchaseitem whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    @Override
    public EnPurchaseitem whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
