// @formatter:off
/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.impl.scheme.tables;


import br.com.wdc.shopping.persistence.impl.scheme.Public;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EnPurchase extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    public static final EnPurchase EN_PURCHASE = new EnPurchase();

    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    public final TableField<Record, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false), this, "");

    public final TableField<Record, Long> USERID = createField(DSL.name("USERID"), SQLDataType.BIGINT.nullable(false), this, "");

    public final TableField<Record, LocalDateTime> BUYDATE = createField(DSL.name("BUYDATE"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private EnPurchase(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private EnPurchase(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    public EnPurchase(String alias) {
        this(DSL.name(alias), EN_PURCHASE);
    }

    public EnPurchase(Name alias) {
        this(alias, EN_PURCHASE);
    }

    public EnPurchase() {
        this(DSL.name("EN_PURCHASE"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(EnPurchase.EN_PURCHASE, DSL.name("PK_PURCHASE"), new TableField[] { EnPurchase.EN_PURCHASE.ID }, true);
    }

    @Override
    public EnPurchase as(String alias) {
        return new EnPurchase(DSL.name(alias), this);
    }

    @Override
    public EnPurchase as(Name alias) {
        return new EnPurchase(alias, this);
    }

    @Override
    public EnPurchase as(Table<?> alias) {
        return new EnPurchase(alias.getQualifiedName(), this);
    }

    @Override
    public EnPurchase rename(String name) {
        return new EnPurchase(DSL.name(name), null);
    }

    @Override
    public EnPurchase rename(Name name) {
        return new EnPurchase(name, null);
    }

    @Override
    public EnPurchase rename(Table<?> name) {
        return new EnPurchase(name.getQualifiedName(), null);
    }

    @Override
    public EnPurchase where(Condition condition) {
        return new EnPurchase(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    @Override
    public EnPurchase where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    @Override
    public EnPurchase where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    @Override
    public EnPurchase where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    @Override
    @PlainSQL
    public EnPurchase where(SQL condition) {
        return where(DSL.condition(condition));
    }

    @Override
    @PlainSQL
    public EnPurchase where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    @Override
    @PlainSQL
    public EnPurchase where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    @Override
    @PlainSQL
    public EnPurchase where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    @Override
    public EnPurchase whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    @Override
    public EnPurchase whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
