/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.impl.scheme.tables;


import br.com.wdc.shopping.persistence.impl.scheme.Keys;
import br.com.wdc.shopping.persistence.impl.scheme.Public;
import br.com.wdc.shopping.persistence.impl.scheme.tables.EnProduct.EnProductPath;
import br.com.wdc.shopping.persistence.impl.scheme.tables.EnPurchase.EnPurchasePath;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EnPurchaseitem extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC.EN_PURCHASEITEM</code>
     */
    public static final EnPurchaseitem EN_PURCHASEITEM = new EnPurchaseitem();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>PUBLIC.EN_PURCHASEITEM.ID</code>.
     */
    public final TableField<Record, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.EN_PURCHASEITEM.PURCHASEID</code>.
     */
    public final TableField<Record, Long> PURCHASEID = createField(DSL.name("PURCHASEID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.EN_PURCHASEITEM.PRODUCTID</code>.
     */
    public final TableField<Record, Long> PRODUCTID = createField(DSL.name("PRODUCTID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.EN_PURCHASEITEM.AMOUNT</code>.
     */
    public final TableField<Record, Integer> AMOUNT = createField(DSL.name("AMOUNT"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.EN_PURCHASEITEM.PRICE</code>.
     */
    public final TableField<Record, BigDecimal> PRICE = createField(DSL.name("PRICE"), SQLDataType.DECIMAL(20, 2).nullable(false), this, "");

    private EnPurchaseitem(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private EnPurchaseitem(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>PUBLIC.EN_PURCHASEITEM</code> table reference
     */
    public EnPurchaseitem(String alias) {
        this(DSL.name(alias), EN_PURCHASEITEM);
    }

    /**
     * Create an aliased <code>PUBLIC.EN_PURCHASEITEM</code> table reference
     */
    public EnPurchaseitem(Name alias) {
        this(alias, EN_PURCHASEITEM);
    }

    /**
     * Create a <code>PUBLIC.EN_PURCHASEITEM</code> table reference
     */
    public EnPurchaseitem() {
        this(DSL.name("EN_PURCHASEITEM"), null);
    }

    public <O extends Record> EnPurchaseitem(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, EN_PURCHASEITEM);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class EnPurchaseitemPath extends EnPurchaseitem implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> EnPurchaseitemPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private EnPurchaseitemPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public EnPurchaseitemPath as(String alias) {
            return new EnPurchaseitemPath(DSL.name(alias), this);
        }

        @Override
        public EnPurchaseitemPath as(Name alias) {
            return new EnPurchaseitemPath(alias, this);
        }

        @Override
        public EnPurchaseitemPath as(Table<?> alias) {
            return new EnPurchaseitemPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.PK_PURCHASEITEM;
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.FK_PURCHASEITEM_PRODUCT, Keys.FK_PURCHASEITEM_PURCHASE);
    }

    private transient EnProductPath _enProduct;

    /**
     * Get the implicit join path to the <code>PUBLIC.EN_PRODUCT</code> table.
     */
    public EnProductPath enProduct() {
        if (_enProduct == null)
            _enProduct = new EnProductPath(this, Keys.FK_PURCHASEITEM_PRODUCT, null);

        return _enProduct;
    }

    private transient EnPurchasePath _enPurchase;

    /**
     * Get the implicit join path to the <code>PUBLIC.EN_PURCHASE</code> table.
     */
    public EnPurchasePath enPurchase() {
        if (_enPurchase == null)
            _enPurchase = new EnPurchasePath(this, Keys.FK_PURCHASEITEM_PURCHASE, null);

        return _enPurchase;
    }

    @Override
    public EnPurchaseitem as(String alias) {
        return new EnPurchaseitem(DSL.name(alias), this);
    }

    @Override
    public EnPurchaseitem as(Name alias) {
        return new EnPurchaseitem(alias, this);
    }

    @Override
    public EnPurchaseitem as(Table<?> alias) {
        return new EnPurchaseitem(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public EnPurchaseitem rename(String name) {
        return new EnPurchaseitem(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EnPurchaseitem rename(Name name) {
        return new EnPurchaseitem(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public EnPurchaseitem rename(Table<?> name) {
        return new EnPurchaseitem(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnPurchaseitem where(Condition condition) {
        return new EnPurchaseitem(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnPurchaseitem where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnPurchaseitem where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnPurchaseitem where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EnPurchaseitem where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EnPurchaseitem where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EnPurchaseitem where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EnPurchaseitem where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnPurchaseitem whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnPurchaseitem whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
