/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.impl.scheme.tables;


import br.com.wdc.shopping.persistence.impl.scheme.Keys;
import br.com.wdc.shopping.persistence.impl.scheme.Public;
import br.com.wdc.shopping.persistence.impl.scheme.tables.EnPurchase.EnPurchasePath;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EnUser extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC.EN_USER</code>
     */
    public static final EnUser EN_USER = new EnUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>PUBLIC.EN_USER.ID</code>.
     */
    public final TableField<Record, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.EN_USER.USERNAME</code>.
     */
    public final TableField<Record, String> USERNAME = createField(DSL.name("USERNAME"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.EN_USER.PASSWORD</code>.
     */
    public final TableField<Record, String> PASSWORD = createField(DSL.name("PASSWORD"), SQLDataType.CHAR(32).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.EN_USER.NAME</code>.
     */
    public final TableField<Record, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.EN_USER.ROLES</code>.
     */
    public final TableField<Record, String> ROLES = createField(DSL.name("ROLES"), SQLDataType.VARCHAR(255), this, "");

    private EnUser(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private EnUser(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>PUBLIC.EN_USER</code> table reference
     */
    public EnUser(String alias) {
        this(DSL.name(alias), EN_USER);
    }

    /**
     * Create an aliased <code>PUBLIC.EN_USER</code> table reference
     */
    public EnUser(Name alias) {
        this(alias, EN_USER);
    }

    /**
     * Create a <code>PUBLIC.EN_USER</code> table reference
     */
    public EnUser() {
        this(DSL.name("EN_USER"), null);
    }

    public <O extends Record> EnUser(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, EN_USER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class EnUserPath extends EnUser implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> EnUserPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private EnUserPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public EnUserPath as(String alias) {
            return new EnUserPath(DSL.name(alias), this);
        }

        @Override
        public EnUserPath as(Name alias) {
            return new EnUserPath(alias, this);
        }

        @Override
        public EnUserPath as(Table<?> alias) {
            return new EnUserPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.PK_USER;
    }

    private transient EnPurchasePath _enPurchase;

    /**
     * Get the implicit to-many join path to the <code>PUBLIC.EN_PURCHASE</code>
     * table
     */
    public EnPurchasePath enPurchase() {
        if (_enPurchase == null)
            _enPurchase = new EnPurchasePath(this, null, Keys.FK_PURCHASE_USER.getInverseKey());

        return _enPurchase;
    }

    @Override
    public EnUser as(String alias) {
        return new EnUser(DSL.name(alias), this);
    }

    @Override
    public EnUser as(Name alias) {
        return new EnUser(alias, this);
    }

    @Override
    public EnUser as(Table<?> alias) {
        return new EnUser(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public EnUser rename(String name) {
        return new EnUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EnUser rename(Name name) {
        return new EnUser(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public EnUser rename(Table<?> name) {
        return new EnUser(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnUser where(Condition condition) {
        return new EnUser(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnUser where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnUser where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnUser where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EnUser where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EnUser where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EnUser where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EnUser where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnUser whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnUser whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
