// @formatter:off
/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.impl.scheme.tables;


import br.com.wdc.shopping.persistence.impl.scheme.Public;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EnUser extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    public static final EnUser EN_USER = new EnUser();

    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    public final TableField<Record, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false), this, "");

    public final TableField<Record, String> USERNAME = createField(DSL.name("USERNAME"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    public final TableField<Record, String> PASSWORD = createField(DSL.name("PASSWORD"), SQLDataType.CHAR(32).nullable(false), this, "");

    public final TableField<Record, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    public final TableField<Record, String> ROLES = createField(DSL.name("ROLES"), SQLDataType.VARCHAR(255), this, "");

    private EnUser(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private EnUser(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    public EnUser(String alias) {
        this(DSL.name(alias), EN_USER);
    }

    public EnUser(Name alias) {
        this(alias, EN_USER);
    }

    public EnUser() {
        this(DSL.name("EN_USER"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(EnUser.EN_USER, DSL.name("PK_USER"), new TableField[] { EnUser.EN_USER.ID }, true);
    }

    @Override
    public EnUser as(String alias) {
        return new EnUser(DSL.name(alias), this);
    }

    @Override
    public EnUser as(Name alias) {
        return new EnUser(alias, this);
    }

    @Override
    public EnUser as(Table<?> alias) {
        return new EnUser(alias.getQualifiedName(), this);
    }

    @Override
    public EnUser rename(String name) {
        return new EnUser(DSL.name(name), null);
    }

    @Override
    public EnUser rename(Name name) {
        return new EnUser(name, null);
    }

    @Override
    public EnUser rename(Table<?> name) {
        return new EnUser(name.getQualifiedName(), null);
    }

    @Override
    public EnUser where(Condition condition) {
        return new EnUser(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    @Override
    public EnUser where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    @Override
    public EnUser where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    @Override
    public EnUser where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    @Override
    @PlainSQL
    public EnUser where(SQL condition) {
        return where(DSL.condition(condition));
    }

    @Override
    @PlainSQL
    public EnUser where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    @Override
    @PlainSQL
    public EnUser where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    @Override
    @PlainSQL
    public EnUser where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    @Override
    public EnUser whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    @Override
    public EnUser whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
