// @formatter:off
/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.impl.scheme.routines;


import br.com.wdc.shopping.persistence.impl.scheme.Public;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ToBase64 extends AbstractRoutine<String> {

    private static final long serialVersionUID = 1L;

    public static final Parameter<String> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.VARCHAR, false, false);

    public static final Parameter<byte[]> P1 = Internal.createParameter("P1", SQLDataType.VARBINARY(1000000000), false, false);

    public ToBase64() {
        super("TO_BASE64", Public.PUBLIC, SQLDataType.VARCHAR);

        setReturnParameter(RETURN_VALUE);
        addInParameter(P1);
    }

    public void setP1(byte[] value) {
        setValue(P1, value);
    }

    public void setP1(Field<byte[]> field) {
        setField(P1, field);
    }
}
