/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.jooq;


import br.com.wdc.shopping.persistence.jooq.tables.EnProduct;
import br.com.wdc.shopping.persistence.jooq.tables.EnPurchase;
import br.com.wdc.shopping.persistence.jooq.tables.EnPurchaseitem;
import br.com.wdc.shopping.persistence.jooq.tables.EnUser;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.EN_PRODUCT</code>.
     */
    public final EnProduct EN_PRODUCT = EnProduct.EN_PRODUCT;

    /**
     * The table <code>PUBLIC.EN_PURCHASE</code>.
     */
    public final EnPurchase EN_PURCHASE = EnPurchase.EN_PURCHASE;

    /**
     * The table <code>PUBLIC.EN_PURCHASEITEM</code>.
     */
    public final EnPurchaseitem EN_PURCHASEITEM = EnPurchaseitem.EN_PURCHASEITEM;

    /**
     * The table <code>PUBLIC.EN_USER</code>.
     */
    public final EnUser EN_USER = EnUser.EN_USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.SQ_PRODUCT,
            Sequences.SQ_PURCHASE,
            Sequences.SQ_PURCHASEITEM,
            Sequences.SQ_USER
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            EnProduct.EN_PRODUCT,
            EnPurchase.EN_PURCHASE,
            EnPurchaseitem.EN_PURCHASEITEM,
            EnUser.EN_USER
        );
    }
}
