/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.jooq.tables;


import br.com.wdc.shopping.persistence.jooq.Keys;
import br.com.wdc.shopping.persistence.jooq.Public;
import br.com.wdc.shopping.persistence.jooq.tables.EnPurchaseitem.EnPurchaseitemPath;
import br.com.wdc.shopping.persistence.jooq.tables.EnUser.EnUserPath;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EnPurchase extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC.EN_PURCHASE</code>
     */
    public static final EnPurchase EN_PURCHASE = new EnPurchase();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>PUBLIC.EN_PURCHASE.ID</code>.
     */
    public final TableField<Record, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.EN_PURCHASE.USERID</code>.
     */
    public final TableField<Record, Long> USERID = createField(DSL.name("USERID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.EN_PURCHASE.BUYDATE</code>.
     */
    public final TableField<Record, LocalDateTime> BUYDATE = createField(DSL.name("BUYDATE"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private EnPurchase(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private EnPurchase(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>PUBLIC.EN_PURCHASE</code> table reference
     */
    public EnPurchase(String alias) {
        this(DSL.name(alias), EN_PURCHASE);
    }

    /**
     * Create an aliased <code>PUBLIC.EN_PURCHASE</code> table reference
     */
    public EnPurchase(Name alias) {
        this(alias, EN_PURCHASE);
    }

    /**
     * Create a <code>PUBLIC.EN_PURCHASE</code> table reference
     */
    public EnPurchase() {
        this(DSL.name("EN_PURCHASE"), null);
    }

    public <O extends Record> EnPurchase(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, EN_PURCHASE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class EnPurchasePath extends EnPurchase implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> EnPurchasePath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private EnPurchasePath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public EnPurchasePath as(String alias) {
            return new EnPurchasePath(DSL.name(alias), this);
        }

        @Override
        public EnPurchasePath as(Name alias) {
            return new EnPurchasePath(alias, this);
        }

        @Override
        public EnPurchasePath as(Table<?> alias) {
            return new EnPurchasePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.PK_PURCHASE;
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.FK_PURCHASE_USER);
    }

    private transient EnUserPath _enUser;

    /**
     * Get the implicit join path to the <code>PUBLIC.EN_USER</code> table.
     */
    public EnUserPath enUser() {
        if (_enUser == null)
            _enUser = new EnUserPath(this, Keys.FK_PURCHASE_USER, null);

        return _enUser;
    }

    private transient EnPurchaseitemPath _enPurchaseitem;

    /**
     * Get the implicit to-many join path to the
     * <code>PUBLIC.EN_PURCHASEITEM</code> table
     */
    public EnPurchaseitemPath enPurchaseitem() {
        if (_enPurchaseitem == null)
            _enPurchaseitem = new EnPurchaseitemPath(this, null, Keys.FK_PURCHASEITEM_PURCHASE.getInverseKey());

        return _enPurchaseitem;
    }

    @Override
    public EnPurchase as(String alias) {
        return new EnPurchase(DSL.name(alias), this);
    }

    @Override
    public EnPurchase as(Name alias) {
        return new EnPurchase(alias, this);
    }

    @Override
    public EnPurchase as(Table<?> alias) {
        return new EnPurchase(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public EnPurchase rename(String name) {
        return new EnPurchase(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EnPurchase rename(Name name) {
        return new EnPurchase(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public EnPurchase rename(Table<?> name) {
        return new EnPurchase(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnPurchase where(Condition condition) {
        return new EnPurchase(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnPurchase where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnPurchase where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnPurchase where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EnPurchase where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EnPurchase where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EnPurchase where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EnPurchase where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnPurchase whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnPurchase whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
