/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.impl.jooq;


import br.com.wdc.shopping.persistence.impl.jooq.tables.EnProduct;
import br.com.wdc.shopping.persistence.impl.jooq.tables.EnPurchase;
import br.com.wdc.shopping.persistence.impl.jooq.tables.EnPurchaseitem;
import br.com.wdc.shopping.persistence.impl.jooq.tables.EnUser;

import org.jooq.ForeignKey;
import org.jooq.Record;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<Record> PK_PRODUCT = Internal.createUniqueKey(EnProduct.EN_PRODUCT, DSL.name("PK_PRODUCT"), new TableField[] { EnProduct.EN_PRODUCT.ID }, true);
    public static final UniqueKey<Record> PK_PURCHASE = Internal.createUniqueKey(EnPurchase.EN_PURCHASE, DSL.name("PK_PURCHASE"), new TableField[] { EnPurchase.EN_PURCHASE.ID }, true);
    public static final UniqueKey<Record> PK_PURCHASEITEM = Internal.createUniqueKey(EnPurchaseitem.EN_PURCHASEITEM, DSL.name("PK_PURCHASEITEM"), new TableField[] { EnPurchaseitem.EN_PURCHASEITEM.ID }, true);
    public static final UniqueKey<Record> PK_USER = Internal.createUniqueKey(EnUser.EN_USER, DSL.name("PK_USER"), new TableField[] { EnUser.EN_USER.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<Record, Record> FK_PURCHASE_USER = Internal.createForeignKey(EnPurchase.EN_PURCHASE, DSL.name("FK_PURCHASE_USER"), new TableField[] { EnPurchase.EN_PURCHASE.USERID }, Keys.PK_USER, new TableField[] { EnUser.EN_USER.ID }, true);
    public static final ForeignKey<Record, Record> FK_PURCHASEITEM_PRODUCT = Internal.createForeignKey(EnPurchaseitem.EN_PURCHASEITEM, DSL.name("FK_PURCHASEITEM_PRODUCT"), new TableField[] { EnPurchaseitem.EN_PURCHASEITEM.PRODUCTID }, Keys.PK_PRODUCT, new TableField[] { EnProduct.EN_PRODUCT.ID }, true);
    public static final ForeignKey<Record, Record> FK_PURCHASEITEM_PURCHASE = Internal.createForeignKey(EnPurchaseitem.EN_PURCHASEITEM, DSL.name("FK_PURCHASEITEM_PURCHASE"), new TableField[] { EnPurchaseitem.EN_PURCHASEITEM.PURCHASEID }, Keys.PK_PURCHASE, new TableField[] { EnPurchase.EN_PURCHASE.ID }, true);
}
