/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.impl.jooq;


import br.com.wdc.shopping.persistence.impl.jooq.tables.EnProduct;
import br.com.wdc.shopping.persistence.impl.jooq.tables.EnPurchase;
import br.com.wdc.shopping.persistence.impl.jooq.tables.EnPurchaseitem;
import br.com.wdc.shopping.persistence.impl.jooq.tables.EnUser;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>PUBLIC.EN_PRODUCT</code>.
     */
    public static final EnProduct EN_PRODUCT = EnProduct.EN_PRODUCT;

    /**
     * The table <code>PUBLIC.EN_PURCHASE</code>.
     */
    public static final EnPurchase EN_PURCHASE = EnPurchase.EN_PURCHASE;

    /**
     * The table <code>PUBLIC.EN_PURCHASEITEM</code>.
     */
    public static final EnPurchaseitem EN_PURCHASEITEM = EnPurchaseitem.EN_PURCHASEITEM;

    /**
     * The table <code>PUBLIC.EN_USER</code>.
     */
    public static final EnUser EN_USER = EnUser.EN_USER;
}
