// @formatter:off
/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.impl.scheme;


import br.com.wdc.shopping.persistence.impl.scheme.tables.EnProduct;
import br.com.wdc.shopping.persistence.impl.scheme.tables.EnPurchase;
import br.com.wdc.shopping.persistence.impl.scheme.tables.EnPurchaseitem;
import br.com.wdc.shopping.persistence.impl.scheme.tables.EnUser;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    public static final Public PUBLIC = new Public();

    public final EnProduct EN_PRODUCT = EnProduct.EN_PRODUCT;

    public final EnPurchase EN_PURCHASE = EnPurchase.EN_PURCHASE;

    public final EnPurchaseitem EN_PURCHASEITEM = EnPurchaseitem.EN_PURCHASEITEM;

    public final EnUser EN_USER = EnUser.EN_USER;

    private Public() {
        super("PUBLIC", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.SQ_PRODUCT,
            Sequences.SQ_PURCHASE,
            Sequences.SQ_PURCHASEITEM,
            Sequences.SQ_USER
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            EnProduct.EN_PRODUCT,
            EnPurchase.EN_PURCHASE,
            EnPurchaseitem.EN_PURCHASEITEM,
            EnUser.EN_USER
        );
    }
}
