/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.impl.scheme;


import br.com.wdc.shopping.persistence.impl.scheme.routines.ToBase64;

import org.jooq.Configuration;
import org.jooq.Field;


/**
 * Convenience access to all stored procedures and functions in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routines {

    /**
     * Call <code>PUBLIC.TO_BASE64</code>
     */
    public static String toBase64(
          Configuration configuration
        , byte[] p1
    ) {
        ToBase64 f = new ToBase64();
        f.setP1(p1);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>PUBLIC.TO_BASE64</code> as a field.
     */
    public static Field<String> toBase64(
          byte[] p1
    ) {
        ToBase64 f = new ToBase64();
        f.setP1(p1);

        return f.asField();
    }

    /**
     * Get <code>PUBLIC.TO_BASE64</code> as a field.
     */
    public static Field<String> toBase64(
          Field<byte[]> p1
    ) {
        ToBase64 f = new ToBase64();
        f.setP1(p1);

        return f.asField();
    }
}
