// @formatter:off
/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.impl.scheme;


import br.com.wdc.shopping.persistence.impl.scheme.routines.ToBase64;

import org.jooq.Configuration;
import org.jooq.Field;


@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routines {

    public static String toBase64(
          Configuration configuration
        , byte[] p1
    ) {
        ToBase64 f = new ToBase64();
        f.setP1(p1);

        f.execute(configuration);
        return f.getReturnValue();
    }

    public static Field<String> toBase64(
          byte[] p1
    ) {
        ToBase64 f = new ToBase64();
        f.setP1(p1);

        return f.asField();
    }

    public static Field<String> toBase64(
          Field<byte[]> p1
    ) {
        ToBase64 f = new ToBase64();
        f.setP1(p1);

        return f.asField();
    }
}
