// @formatter:off
/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.impl.scheme;


import br.com.wdc.shopping.persistence.impl.scheme.tables.EnProduct;
import br.com.wdc.shopping.persistence.impl.scheme.tables.EnPurchase;
import br.com.wdc.shopping.persistence.impl.scheme.tables.EnPurchaseitem;
import br.com.wdc.shopping.persistence.impl.scheme.tables.EnUser;


@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    public static final EnProduct EN_PRODUCT = EnProduct.EN_PRODUCT;

    public static final EnPurchase EN_PURCHASE = EnPurchase.EN_PURCHASE;

    public static final EnPurchaseitem EN_PURCHASEITEM = EnPurchaseitem.EN_PURCHASEITEM;

    public static final EnUser EN_USER = EnUser.EN_USER;
}
